// const TANK_KEY_ROTATE_L = 65"TANK_KEY_ROTATE_L"
// const TANK_KEY_ROTATE_R = 68
// const TANK_KEY_BASE_ROTATE_R = 69
// const TANK_KEY_BASE_ROTATE_L = 81
// const TANK_KEY_MOVE_F = 87
// const TANK_KEY_MOVE_B = 83
// const TANK_KEY_FIRE = 32



const KEYS = {
    TANK_KEY_ROTATE_L: 65,
    TANK_KEY_ROTATE_R: 68,
    TANK_KEY_BASE_ROTATE_R: 69,
    TANK_KEY_BASE_ROTATE_L: 81,
    TANK_KEY_MOVE_F: 87,
    TANK_KEY_MOVE_B: 83,
    TANK_KEY_FIRE: 32
}

// export default TANK_KEY_ROTATE_L, TANK_KEY_ROTATE_R, TANK_KEY_BASE_ROTATE_R, TANK_KEY_BASE_ROTATE_L, TANK_KEY_MOVE_F, TANK_KEY_MOVE_B, TANK_KEY_FIRE

export default KEYS